export const topics = [
  { id: 1, title: "Divorce and Breakup", value: 21, abbr: "DIV", color: "red" },
  {
    id: 2,
    title: "Relationship and Courtship Journey",
    value: 20,
    abbr: "REL",
    color: "green",
  },
  {
    id: 3,
    title: "Occupation and Career",
    value: 10,
    abbr: "OCC",
    color: "yellow",
  },
  {
    id: 4,
    title: "Marriage Experience",
    value: 222,
    abbr: "MAR",
    color: "blue",
  },
  { id: 5, title: "Intimacy", value: 20, abbr: "INT", color: "orange" },
  { id: 6, title: "Wedding", value: 20, abbr: "WED", color: "purple" },
  {
    id: 7,
    title: "Newly Wed Experience",
    value: 21,
    abbr: "NEW",
    color: "red",
  },
  { id: 8, title: "Single Parenting", value: 20, abbr: "SIN", color: "green" },
  { id: 9, title: "TTC", value: 10, abbr: "TTC", color: "yellow" },
  {
    id: 10,
    title: "Religion/Spirituality",
    value: 222,
    abbr: "SPI",
    color: "blue",
  },
  { id: 11, title: "Health", value: 20, abbr: "HEA", color: "orange" },
  { id: 12, title: "Fashion", value: 20, abbr: "FAS", color: "purple" },
  { id: 13, title: "Parental Journey", value: 21, abbr: "PAR", color: "red" },
  { id: 14, title: "Social Life", value: 20, abbr: "SOC", color: "green" },
  {
    id: 15,
    title: "Aid and Help (Let Love Lead)",
    value: 10,
    abbr: "AID",
    color: "yellow",
  },
  {
    id: 16,
    title: "Do It Yourself (DIY)",
    value: 222,
    abbr: "DIY",
    color: "blue",
  },
  {
    id: 17,
    title: "Pregnancy Experience",
    value: 20,
    abbr: "PRE",
    color: "orange",
  },
];
